raw_input('SitDown...')
p.playBehavior('SitDown')
#
raw_input('LowDriveForward...')
p.playBehavior('LowDriveForward')
#
raw_input('StandUp...')
p.playBehavior('StandUp')
#
raw_input('TurnForward...')
p.playBehavior('TurnForward')
#
raw_input('HighDriveForward...')
p.playBehavior('HighDriveForward')
#
raw_input('TurnNeutral...')
p.playBehavior('TurnNeutral')
#
raw_input('SitDown...')
p.playBehavior('SitDown')
#
raw_input('LowDriveBackward...')
p.playBehavior('LowDriveBackward')
#
raw_input('StandUp...')
p.playBehavior('StandUp')